#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
FONT="JetBrainsMono Nerd Font"

##### Bar Appearance #####
sketchybar --bar position=top \
                 height=33 \
                 blur_radius=30 \
                 color=0xcc1e1e2e \
                 border_color=0xff2e2e3e \
                 shadow=off \
                 sticky=on \
                 padding_left=6 \
                 padding_right=6 \
                 topmost=window

##### Changing Defaults #####
default=(
  padding_left=6
  padding_right=6
  icon.font="$FONT:Bold:11.0"
  label.font="$FONT:Regular:11.0"
  icon.color=0xffcad3f5
  label.color=0xffcad3f5
  icon.padding_left=3
  icon.padding_right=3
  label.padding_left=3
  label.padding_right=3
  background.height=20
  background.corner_radius=4
)
sketchybar --default "${default[@]}"

##### Aerospace Workspace Indicators #####
sketchybar --add event aerospace_workspace_change

for sid in 1 2 3 4 5 6; do
  sketchybar --add item space.$sid left \
             --set space.$sid icon="$sid" \
                              icon.padding_left=10 \
                              icon.padding_right=10 \
                              label.drawing=off \
                              background.color=0x00000000 \
                              background.drawing=on \
                              script="$PLUGIN_DIR/aerospace.sh $sid" \
             --subscribe space.$sid aerospace_workspace_change
done

##### Right Items #####
# Clock
sketchybar --add item clock right \
           --set clock update_freq=1 \
                       icon.drawing=off \
                       label.font="$FONT:Bold:11.0" \
                       script="$PLUGIN_DIR/clock.sh"

# Battery
sketchybar --add item battery right \
           --set battery update_freq=60 \
                         script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

# CPU
sketchybar --add item cpu right \
           --set cpu update_freq=5 \
                     script="$PLUGIN_DIR/cpu.sh"

# Memory
sketchybar --add item memory right \
           --set memory update_freq=5 \
                        script="$PLUGIN_DIR/memory.sh"

# Network
sketchybar --add item network right \
           --set network update_freq=3 \
                          script="$PLUGIN_DIR/network.sh"

##### Force all scripts to run the first time #####
sketchybar --update
