#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
FONT="JetBrainsMono Nerd Font"

##### Bar Appearance #####
sketchybar --bar position=top \
                 height=24 \
                 notch_display_height=33 \
                 blur_radius=30 \
                 color=0xf0080808 \
                 border_color=0xff2e2e3e \
                 shadow=off \
                 sticky=on \
                 padding_left=6 \
                 padding_right=12 \
                 topmost=window \
                 font_smoothing=on

##### Changing Defaults #####
default=(
  padding_left=3
  padding_right=3
  icon.font="$FONT:Bold:11.0"
  label.font="$FONT:Regular:11.0"
  icon.color=0xffcad3f5
  label.color=0xffcad3f5
  icon.drawing=off
  label.padding_left=3
  label.padding_right=3
  background.drawing=off
  updates=when_shown
)
sketchybar --default "${default[@]}"

##### Aerospace Workspace Indicators #####
sketchybar --add event aerospace_workspace_change

for sid in 1 2 3 4 5 6; do
  sketchybar --add item space.$sid left \
             --set space.$sid label="$sid" \
                              label.padding_left=6 \
                              label.padding_right=6 \
                              updates=on \
                              script="$PLUGIN_DIR/aerospace.sh $sid" \
             --subscribe space.$sid aerospace_workspace_change
done

sketchybar --add item front_app left \
           --set front_app label.padding_left=8 \
                           updates=on \
                           script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Right Items #####
sketchybar --add item clock right \
           --set clock update_freq=1 \
                       label.font="$FONT:Bold:11.0" \
                       label.width=120 \
                       label.align=right \
                       script="$PLUGIN_DIR/clock.sh" \
                       updates=on \
           \
           --add item battery right \
           --set battery update_freq=60 \
                         label.width=dynamic \
                         script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \
           \
           --add item cpu right \
           --set cpu update_freq=5 \
                     label.width=dynamic \
                     script="$PLUGIN_DIR/cpu.sh" \
           \
           --add item memory right \
           --set memory update_freq=5 \
                        label.width=dynamic \
                        script="$PLUGIN_DIR/memory.sh" \
           \
           --add item network right \
           --set network update_freq=3 \
                          label.width=dynamic \
                          script="$PLUGIN_DIR/network.sh"

# Display change handler
sketchybar --add item display_handler center \
           --set display_handler drawing=off \
                                 updates=on \
                                 script="$HOME/.config/aerospace/gap-toggle.sh" \
           --subscribe display_handler display_change system_woke

##### Force all scripts to run the first time #####
sketchybar --update
