enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

on-focus-changed = 'move-mouse window-lazy-center'

automatically-unhide-macos-hidden-apps = true

after-startup-command = [
  'exec-and-forget ~/.config/aerospace/gap-toggle.sh'
]

on-focused-monitor-changed = ['move-mouse monitor-lazy-center', 'exec-and-forget ~/.config/aerospace/gap-toggle.sh']

# Notify sketchybar on workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[gaps]
outer.top = 24
outer.bottom = 0
outer.left = 0
outer.right = 0
inner.horizontal = 0
inner.vertical = 0

[[on-window-detected]]
    if.app-id = 'com.apple.systempreferences'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.apple.finder'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.microsoft.teams2'
    run = 'move-node-to-workspace 3'

[[on-window-detected]]
    if.app-id = 'com.microsoft.Outlook'
    run = 'move-node-to-workspace 3'

[[on-window-detected]]
    if.app-id = 'com.tinyspeck.slackmacgap'
    run = 'move-node-to-workspace 3'

[[on-window-detected]]
    if.app-id = 'com.DanPristupov.Fork'
    run = ['layout floating', 'move-node-to-workspace 5']

[[on-window-detected]]
    if.app-id = 'com.linear'
    run = 'move-node-to-workspace 5'

[mode.main.binding]
    ctrl-alt-cmd-t = "exec-and-forget open -n -a ghostty"
    ctrl-alt-cmd-e = "exec-and-forget open -n -a helium"
    ctrl-alt-cmd-q = "close --quit-if-last-window"

    ctrl-alt-cmd-j =         'focus --boundaries-action wrap-around-the-workspace left'
    ctrl-alt-cmd-k =         'focus --boundaries-action wrap-around-the-workspace down'
    ctrl-alt-cmd-l =         'focus --boundaries-action wrap-around-the-workspace up'
    ctrl-alt-cmd-semicolon = 'focus --boundaries-action wrap-around-the-workspace right'

    ctrl-alt-cmd-shift-j = 'move left'
    ctrl-alt-cmd-shift-k = 'move down'
    ctrl-alt-cmd-shift-l = 'move up'
    ctrl-alt-cmd-shift-semicolon = 'move right'

    ctrl-alt-cmd-shift-period = "move-workspace-to-monitor next"
    ctrl-alt-cmd-shift-comma  = "move-workspace-to-monitor prev"

    ctrl-alt-cmd-f = 'fullscreen'

    ctrl-alt-cmd-s = 'layout v_accordion'
    ctrl-alt-cmd-w = 'layout h_accordion'

    ctrl-alt-cmd-shift-space = 'layout floating tiling'
    ctrl-alt-cmd-shift-f = 'flatten-workspace-tree'

    ctrl-alt-cmd-shift-n = 'move-node-to-monitor next'
    ctrl-alt-cmd-shift-p = 'move-node-to-monitor prev'

    ctrl-alt-cmd-tab = 'workspace-back-and-forth'

    ctrl-alt-cmd-1 = 'workspace 1'
    ctrl-alt-cmd-2 = 'workspace 2'
    ctrl-alt-cmd-3 = 'workspace 3'
    ctrl-alt-cmd-4 = 'workspace 4'
    ctrl-alt-cmd-5 = 'workspace 5'
    ctrl-alt-cmd-6 = 'workspace 6'

    ctrl-alt-cmd-shift-1 = 'move-node-to-workspace 1'
    ctrl-alt-cmd-shift-2 = 'move-node-to-workspace 2'
    ctrl-alt-cmd-shift-3 = 'move-node-to-workspace 3'
    ctrl-alt-cmd-shift-4 = 'move-node-to-workspace 4'
    ctrl-alt-cmd-shift-5 = 'move-node-to-workspace 5'
    ctrl-alt-cmd-shift-6 = 'move-node-to-workspace 6'

    ctrl-alt-cmd-shift-c = 'reload-config'
    ctrl-alt-cmd-r = 'mode resize'
    ctrl-alt-cmd-g = 'mode join'

[mode.join.binding]
    j = ['join-with left', 'mode main']
    k = ['join-with down', 'mode main']
    l = ['join-with up', 'mode main']
    semicolon = ['join-with right', 'mode main']
    enter = 'mode main'
    esc = 'mode main'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'
